components_configurations_folder: ~/w/catkin_ws/src/slam_performance_modelling/config/component_configurations
gazebo_model_path_env_var: [~/ds/performance_modelling/aws-robomaker-small-warehouse-world/models]
gazebo_resource_path_env_var: [~/ds/performance_modelling/aws-robomaker-small-warehouse-world]
gazebo_plugin_path_env_var: [~/w/catkin_ws/build/gazebo_plugins/]
source_workspace_path: ~/w/catkin_ws/src/

supervisor_component: slam_benchmark_supervisor

environment_type: 'dataset'

components_configuration:
  supervisor: slam_benchmark_supervisor/slam_benchmark_supervisor.yaml
  slam_toolbox: slam_toolbox/slam_toolbox_online_async.yaml
  gmapping: gmapping/gmapping.yaml

combinatorial_parameters:
  slam_node: [gmapping]
  particles: [30]
  linear_angular_update: [[0.2, 0.1], [0.5, 0.5]]
  dataset_odom: [original, corrected]
  laser_scan_max_range: [20.0]
  laser_scan_fov_deg: [180]
  map_resolution: [0.05]
