components_configurations_folder: ~/w/catkin_ws/src/slam_performance_modelling/config/component_configurations
gazebo_model_path_env_var: []
gazebo_plugin_path_env_var: [~/w/catkin_ws/build/gazebo_plugins/]

supervisor_component: slam_benchmark_supervisor

components_configuration:
  supervisor: slam_benchmark_supervisor/slam_benchmark_supervisor.yaml
  slam_toolbox: slam_toolbox/slam_toolbox_online_async.yaml
  gmapping: gmapping/gmapping.yaml
  move_base: move_base/move_base_tb3.yaml

combinatorial_parameters:
  slam_node: [slam_toolbox]
  ceres_loss_function: [None, HuberLoss, CauchyLoss]
  beta: [[0.0, 0.0, 0.0, 0.0], [0.035, 0.035, 0.01, 0.01]]
  laser_scan_max_range: [30.0]
  laser_scan_fov_deg: [90, 180, 270, 359]
  map_resolution: [0.05]
