components_configurations_folder: ~/w/catkin_ws/src/slam_performance_modelling/config/component_configurations
gazebo_model_path_env_var: []
gazebo_plugin_path_env_var: [~/w/catkin_ws/build/gazebo_plugins/]

supervisor_component: slam_benchmark_supervisor

components_configuration:
  supervisor: slam_benchmark_supervisor/slam_benchmark_supervisor.yaml
  slam_toolbox: slam_toolbox/slam_toolbox_online_async.yaml
  gmapping: gmapping/gmapping.yaml
  move_base: move_base/move_base_tb3.yaml

combinatorial_parameters:
  slam_node: [gmapping]
  particles: [30]
  linear_update: [0.2]
  angular_update: [0.1]
  beta: [[0.0, 0.0, 0.0, 0.0], [0.035, 0.035, 0.01, 0.01], [0.07, 0.07, 0.02, 0.02]]
  laser_scan_max_range: [3.5, 8.0, 30.0]
  laser_scan_fov_deg: [90, 180, 270, 359]
  map_resolution: [0.05]
